# Lint Rules
opt_in_rules:
  - empty_count
  - force_unwrapping

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

force_cast:
  severity: error

force_try:
  severity: error

line_length:
  warning: 180
  error: 220
  ignores_comments: true
  ignores_function_declarations: true

type_body_length:
  - 300
  - 400

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50

included:
  - Unoriginal
